package IntGrafica;

import Logica.*;
import Parametros.Param;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import static Parametros.Param.*;
import static Ficheros.Ficheros.*;
import javax.swing.JOptionPane;

public class mainFrame extends javax.swing.JFrame {

    Param parametros;
    Camping camp;
    ArrayList<Parcela> parcelas;
    JButton[] botonera;

    public mainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        parametros = new Param(rutaProperties);
        camp = new Camping();
        parcelas = camp.getCamping();
        botonera = new JButton[TOTAL_PARCELAS];
        for (int i = 0; i < botonera.length; i++) {
            botonera[i] = new JButton();
            if(parcelas.get(i).isOcupado()) botonera[i].setBackground(Color.red);
            if (parcelas.get(i) instanceof Bungalow) {
                botonera[i].setText("B " + i);
            } else if (parcelas.get(i) instanceof Caravana) {
                botonera[i].setText("C " + i);
            } else {
                botonera[i].setText("T " + i);
            }
            botonera[i].setName("" + i);
            botonera[i].addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    FActionPerformed(evt);
                }
            });
            PanelCentral.add(botonera[i]);
        }
    }

    public void FActionPerformed(java.awt.event.MouseEvent evt) {
        int pos = Integer.valueOf(((JButton) evt.getSource()).getName());
        Parcela parcela = parcelas.get(pos);
        if(parcela.isOcupado()){
            
            int input = JOptionPane.showConfirmDialog(null, "Aviso", "Quieres librar la parcela?",
				JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if(input == JOptionPane.YES_OPTION){
                System.out.println("Vamos por aca");
            }
        }
        else{
            if(parcela instanceof Bungalow){
                AlquilarBungalow dialog = new AlquilarBungalow(new javax.swing.JFrame(), true, parcela, parametros); 
                dialog.setVisible(true);
            }
            else{
                AlquilarParcela dialog = new AlquilarParcela(new javax.swing.JFrame(), true, parcela); 
                dialog.setVisible(true);
            }
            if(parcela.isOcupado()) ((JButton) evt.getSource()).setBackground(Color.red);
        }
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInferior = new javax.swing.JPanel();
        BotonParametros = new javax.swing.JButton();
        BotonAyuda = new javax.swing.JButton();
        BotonAbout = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        PanelSuperior = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        PanelCentral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Camping");
        setMinimumSize(new java.awt.Dimension(600, 600));

        PanelInferior.setBackground(new java.awt.Color(153, 255, 204));
        PanelInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 7, 5));

        BotonParametros.setText("Parametros");
        PanelInferior.add(BotonParametros);

        BotonAyuda.setText("Ayuda");
        PanelInferior.add(BotonAyuda);

        BotonAbout.setText("About");
        PanelInferior.add(BotonAbout);

        BotonSalir.setText("Salir");
        BotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirMouseClicked(evt);
            }
        });
        PanelInferior.add(BotonSalir);

        getContentPane().add(PanelInferior, java.awt.BorderLayout.PAGE_END);

        PanelSuperior.setBackground(new java.awt.Color(153, 255, 204));

        LabelTitulo.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        LabelTitulo.setForeground(new java.awt.Color(0, 153, 153));
        LabelTitulo.setText("CAMPING DE DDP");
        PanelSuperior.add(LabelTitulo);

        getContentPane().add(PanelSuperior, java.awt.BorderLayout.PAGE_START);

        PanelCentral.setBackground(new java.awt.Color(153, 255, 204));
        PanelCentral.setMinimumSize(new java.awt.Dimension(400, 400));
        PanelCentral.setPreferredSize(new java.awt.Dimension(400, 500));
        PanelCentral.setLayout(new java.awt.GridLayout(10, 8));
        getContentPane().add(PanelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseClicked
        int respuesta = JOptionPane.showConfirmDialog(this, "Vas a Salir del programa. Quieres guardar?");
        if (respuesta == JOptionPane.OK_OPTION) {
            System.out.println("El usuario confirma la operación");
            guardarCamping(parcelas);
            System.exit(0);
        }else if(respuesta == JOptionPane.NO_OPTION){
            System.exit(0);
        }
        
        
    }//GEN-LAST:event_BotonSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAbout;
    private javax.swing.JButton BotonAyuda;
    private javax.swing.JButton BotonParametros;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelInferior;
    private javax.swing.JPanel PanelSuperior;
    // End of variables declaration//GEN-END:variables
}
